# Generated by Django 5.0.4 on 2024-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MEMBER",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("mem_email", models.CharField(max_length=255)),
                ("mem_name", models.CharField(max_length=255)),
                ("mem_imgUrl", models.TextField()),
                ("mem_address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("mem_age", models.IntegerField()),
                ("mem_gender", models.CharField(max_length=50)),
                ("mem_job", models.CharField(max_length=255)),
            ],
        ),
    ]
