# Generated by Django 5.0.4 on 2024-05-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MET_KEYWORD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("met_keyword_id", models.IntegerField()),
                ("keyword_list", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MET_REQUEST",
            fields=[
                ("met_request_id", models.AutoField(primary_key=True, serialize=False)),
                ("insta_url", models.TextField()),
                ("youtub_url", models.TextField()),
                ("et_url", models.TextField()),
                ("re_title", models.CharField(max_length=255)),
                ("re_content", models.TextField()),
                ("date_of_meeting", models.DateField()),
                ("re_supplies", models.CharField(max_length=255)),
                ("re_image", models.ImageField(upload_to="")),
                ("re_meetbrief", models.CharField(max_length=255)),
                ("business_area", models.CharField(max_length=50)),
                ("regular_activity", models.CharField(max_length=10)),
                ("online_offline", models.CharField(max_length=10)),
                ("re_challenge", models.CharField(max_length=10)),
                ("re_category", models.CharField(max_length=10)),
                ("participation_fee", models.IntegerField()),
                ("preparation_materials", models.TextField()),
                ("end_of_positing", models.IntegerField()),
                ("re_bank", models.CharField(max_length=50)),
                ("deposit_account", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MET_ROLE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mem_role_id", models.IntegerField()),
                ("ro_rloe", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("meeting_name", models.CharField(max_length=100)),
                ("ro_position", models.CharField(max_length=100)),
                ("post_id", models.IntegerField()),
                ("mem_deposit", models.BooleanField()),
                ("mem_category", models.CharField(max_length=255)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MET_COMMENT",
            fields=[
                ("met_comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("co_content", models.TextField()),
                ("display_name", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MET_CHALLENGE",
            fields=[
                (
                    "met_challenge_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ch_send", models.CharField(max_length=100)),
                ("ch_send_check", models.BooleanField()),
                ("ch_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MET_CATEGORY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("met_category_id", models.IntegerField()),
                ("met_keyword_id", models.IntegerField()),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MET_ATTENDANCE",
            fields=[
                (
                    "met_attendance_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("attendance_check", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ALM_MESSAGE",
            fields=[
                ("alm_message_id", models.AutoField(primary_key=True, serialize=False)),
                ("me_eta", models.DateField()),
                ("me_send", models.IntegerField()),
                ("me_message", models.TextField()),
                ("me_category", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MET_SURVEY",
            fields=[
                ("met_survey_id", models.AutoField(primary_key=True, serialize=False)),
                ("su_survey", models.TextField()),
                ("su_answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.member"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dbset.met_role"
                    ),
                ),
            ],
        ),
    ]
