# Generated by Django 5.0.4 on 2024-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbset", "0002_met_keyword_met_request_met_role_met_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="met_request",
            name="mbr_age",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="mbr_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="mbr_num",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="participation_check",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="proc_content",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="proc_time",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="proc_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="refund_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="sel_method",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="business_area",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="date_of_meeting",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="deposit_account",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="end_of_positing",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="et_url",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="insta_url",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="online_offline",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="participation_fee",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="preparation_materials",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="re_bank",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="re_challenge",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="re_content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="re_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="re_supplies",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="regular_activity",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="met_request",
            name="youtub_url",
            field=models.TextField(null=True),
        ),
    ]
