# Generated by Django 5.0.4 on 2024-05-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbset", "0003_met_request_mbr_age_met_request_mbr_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="met_request",
            old_name="date_of_meeting",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="met_request",
            old_name="et_url",
            new_name="out_links",
        ),
        migrations.RenameField(
            model_name="met_request",
            old_name="business_area",
            new_name="pick_method",
        ),
        migrations.RenameField(
            model_name="met_request",
            old_name="insta_url",
            new_name="re_payment",
        ),
        migrations.RenameField(
            model_name="met_request",
            old_name="re_content",
            new_name="schedule",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="deposit_account",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="online_offline",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="participation_check",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="participation_fee",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="proc_content",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="proc_time",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="proc_title",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="re_bank",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="refund_content",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="sel_method",
        ),
        migrations.RemoveField(
            model_name="met_request",
            name="youtub_url",
        ),
        migrations.AddField(
            model_name="met_request",
            name="address",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="met_request",
            name="process",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="met_survey",
            name="meet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbset.met_request",
            ),
        ),
        migrations.AlterField(
            model_name="met_survey",
            name="member_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbset.member",
            ),
        ),
        migrations.AlterField(
            model_name="met_survey",
            name="post_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbset.met_role",
            ),
        ),
        migrations.AlterField(
            model_name="met_survey",
            name="su_answer",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="met_survey",
            name="su_survey",
            field=models.TextField(null=True),
        ),
    ]
